# Dockerfile para o Frontend (Nginx)

# Usar a imagem oficial do Nginx
FROM nginx:alpine

# Copiar os arquivos do frontend para o diretório de arquivos estáticos do Nginx
COPY . /usr/share/nginx/html

# Expor a porta 80 (padrão para HTTP)
EXPOSE 80
