version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: restaurante_universitario
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: restaurante_universitario
    ports:
      - "3307:3306"  # Alterando a porta local para 3307
    volumes:
      - ./mysql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
