-- MySQL Script generated by MySQL Workbench
-- Sat Feb  1 19:08:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurante_universitario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante_universitario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS restaurante_universitario DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE restaurante_universitario ;

-- -----------------------------------------------------
-- Table restaurante_universitario.compras
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS restaurante_universitario.compras (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  tipo_comida VARCHAR(50) NOT NULL,
  campus VARCHAR(50) NOT NULL,
  valor DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) NULL DEFAULT 'pendente',
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table restaurante_universitario.usuarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS restaurante_universitario.usuarios (
  id_usuario INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  matricula VARCHAR(20) NOT NULL,
  plano VARCHAR(50) NOT NULL DEFAULT 'Subsidiado',
  PRIMARY KEY (id_usuario),
  UNIQUE INDEX matricula (matricula ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table restaurante_universitario.tickets
-- -----------------------------------------------------

-- Inserindo 10 usuários na tabela 'usuarios'

INSERT INTO usuarios (nome, matricula, plano)
VALUES 
  ('João Silva', '123456', 'Subsidiado'),
  ('Maria Oliveira', '654321', 'Não subsidiado'),
  ('Pedro Santos', '789456', 'Subsidiado'),
  ('Ana Costa', '147258', 'Não subsidiado'),
  ('Carlos Souza', '258369', 'Subsidiado'),
  ('Fernanda Lima', '369258', 'Não subsidiado'),
  ('Lucas Pereira', '456123', 'Subsidiado'),
  ('Juliana Almeida', '987654', 'Não subsidiado'),
  ('Eduardo Martins', '321654', 'Subsidiado'),
  ('Camila Rocha', '741852', 'Não subsidiado');


-- Criando a tabela de administradores
CREATE TABLE IF NOT EXISTS restaurante_universitario.admins (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- Inserindo um administrador de exemplo
INSERT INTO admins (email, senha) VALUES ('admin@exemplo.com', '123456');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;